default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: trestle_examples_test

development:
  <<: *default
  database: trestle_examples_development

production:
  <<: *default
  database: trestle_examples_production
  username: trestle_examples
  password: <%= ENV['TRESTLE_EXAMPLES_DATABASE_PASSWORD'] %>
