default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: db/trestle_examples_test.sqlite3

development:
  <<: *default
  database: db/trestle_examples_development.sqlite3

production:
  <<: *default
  database: db/trestle_examples_production.sqlite3
