test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage/active_storage") %>

amazon:
  service: S3
  access_key_id:     <%= Rails.application.credentials.dig(Rails.env.to_sym, :aws, :s3, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(Rails.env.to_sym, :aws, :s3, :secret_access_key) %>
  bucket:            <%= Rails.application.credentials.dig(Rails.env.to_sym, :aws, :s3, :bucket_name) %>
  region: us-east-1
  upload:
    acl: "public-read"
